version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 744628107553.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-python-terraform-app .
      - docker tag my-python-terraform-app:latest 744628107553.dkr.ecr.us-east-1.amazonaws.com/my-python-terraform-app:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 744628107553.dkr.ecr.us-east-1.amazonaws.com/my-python-terraform-app:latest
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' my-container-terraform-app 744628107553.dkr.ecr.us-east-1.amazonaws.com/my-python-terraform-app:latest > imagedefinitions.json

artifacts:
  files: 
     - appspec.yml
     - imagedefinitions.json
     - '**/*'
  discard-paths: yes
